import localFont from "next/font/local";
import "./globals.css";
import ProtectedRouteAll from "@/components/ProtectedRouteAll/ProtectedRouteAll";
// import ProtectedRoute from "@/components/ProtectedRouteSalesperson/ProtectedRoute";
// import { useRouter } from "next/router";
import { Inter } from 'next/font/google';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // Optional: if you want CSS variable support
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable } ${inter.variable} font-sans antialiased `}>
      <ProtectedRouteAll> 
        {children}
      </ProtectedRouteAll> 
      </body>
    </html>
  );
}



